#!/usr/bin/env bash

# read from stdin or from the first argument
if [ -z "$1" ]; then
  read -r data
else
  data=$1
fi

# loop over the keys and print the .tag_name 

tags=$(echo "$data" | jq -cr 'to_entries | map(.value) | map(.tag_name)')

# create branch for each tag
for tag in $tags; do
  git checkout -b "release/$tag"
  git push origin "release/$tag"    
done