#!/usr/bin/env -S node

//MISE description="Parse release-please output to get the list of released apps field name and values"
//USAGE arg "<json_payload>" help="The release please json payload" default="{}" 

const usage_json_payload = process.env.usage_json_payload


// const mockdata = JSON.stringify({
//   "releases_created": "true",
//   "apps/back-office--release_created": "true",
//   "apps/back-office--id": "208809086",
//   "apps/back-office--name": "back-office: v1.0.0",
//   "apps/back-office--tag_name": "back-office-v1.0.0",
//   "apps/back-office--sha": "a4391647ee1e57994de1176a623188d9b95ec15b",
//   "apps/back-office--body": "## 1.0.0 (2025-03-27)\n\n\n### Features\n\n* configure something ([#9](https://github.com/zenobi-us/release-please-app-monorepo/issues/9)) ([f49277c](https://github.com/zenobi-us/release-please-app-monorepo/commit/f49277cd3cb3cde4ec28bae74bf79526a2dea689))",
//   "apps/back-office--html_url": "https://github.com/zenobi-us/release-please-app-monorepo/releases/tag/back-office-v1.0.0",
//   "apps/back-office--draft": "false",
//   "apps/back-office--upload_url": "https://uploads.github.com/repos/zenobi-us/release-please-app-monorepo/releases/208809086/assets{?name,label}",
//   "apps/back-office--path": "apps/back-office",
//   "apps/back-office--version": "1.0.0",
//   "apps/back-office--major": "1",
//   "apps/back-office--minor": "0",
//   "apps/back-office--patch": "0",
//   "paths_released": "[\"apps/back-office\"]",
//   "prs_created": "false"
// })

function createKeyPairMatcher(pattern) {
  const regex = new RegExp(pattern);
  
  return ([key, value]) => {
    // expect that the pattern has two capture groups
    // the first one is the key and the second one is the value
    const match = regex.exec(key);
    const group = match && match.groups.group;
    const field = match && match.groups.fieldName;
    if (!match) {
        return
    }

    return { group, field, value }

  }
}

function getPathsReleased(data) {
    try {
        return JSON.parse(data);
    } catch (e) {
        return [];
    }
}

function pickFields(data) {
    const apps = getPathsReleased(data.paths_released);
    const pattern = `(?<group>${apps.join('|')})--(?<fieldName>.*)`;
    const matcher = createKeyPairMatcher(pattern)

    return Object.entries(data)
        .map(matcher)
        .filter(Boolean)
        .reduce((acc, data) => {
            acc[data.group] = {
                ...(acc[data.group] || {}),
                [data.field]: data.value
            }
            return acc;
        }, {});
}

if (!usage_json_payload) {
    console.error('usage_json_payload is required');
    process.exit(1);
}

const fields = pickFields(JSON.parse(usage_data));

console.log(JSON.stringify(fields));