#!/usr/bin/env bash

# This script collects all the **/release-manifest.json files in the project and 
# merges them into the "packages" object in the root release-manifest.json file.
# The key for each item in the "packages" object is the relative path of the package directory, and the value is the contents of the release-manifest.json file.

function find_release_manifests {
  find . -name release-manifest.json
}

function merge_package_manifest {
  local release_manifest_path
  local package_manifest_path
  local relative_package_path

  release_manifest_path=$1
  package_manifest_path=$2

  relative_package_path=$(dirname "$package_manifest_path")

  manifest=$(jq -r "$release_manifest_path")
  package=$(jq -r "$package_manifest_path")

    if [ "$manifest" == "null" ]; then
        manifest='{}'
    fi

    if [ "$package" == "null" ]; then
        package='{}'
    fi

    # add package to manifest.packages
    # {
    #   "packages": {
    #      <package_path>: "<package_manifest>"
    #   }
    # }

    manifest=$(jq \
        --arg package_path "$relative_package_path" \
        --argjson package "$package" \
        '.packages[$package_path] = $package' <<< "$manifest")

    echo "$manifest" > "$release_manifest_path"
}

release_manifest_path="release-manifest.json"

find_release_manifests | while read -r package_manifest_path; do
  merge_package_manifest "$release_manifest_path" "$package_manifest_path"
done