name: Publish Package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "npm tag (latest or next)"
        required: true
        type: choice
        options:
          - latest
          - next
  repository_dispatch:
    types: [publish-package]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - id: inputs
        uses: simenandre/setup-inputs@00a2f5d3135898b400343ff87d99b7841e6e4592 # v1

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Setup Toolchain
        uses: moonrepo/setup-toolchain@8794f0318b9df4a43a5ddc23cefd16f595b423dd # v0
        with:
          auto-install: true
          auto-setup: true

      - name: Publish Affected Items
        run: |
          TAG="${{ steps.inputs.outputs.tag }}"
          if [ -z "$TAG" ]; then
            TAG="latest"
          fi

          echo "Publishing with tag: $TAG"
          moon run :publish -- "$TAG"
