name: Release

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      prs_created: ${{ steps.release-please.outputs.prs_created }}
    steps:
      - uses: google-github-actions/release-please-action@a017ec70c7f1401744d60197f7577a0c51c8c1cf # v4
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          skip-github-pull-request: false

  dispatch-publish:
    needs: process
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: needs.process.outputs.releases_created == 'true' || needs.process.outputs.prs_created == 'true'
    steps:
      - name: Dispatch publish for releases
        if: needs.process.outputs.releases_created == 'true'
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: publish-package
          client-payload: '{"tag": "latest"}'

      - name: Dispatch publish for prerelease
        if: needs.process.outputs.prs_created == 'true'
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: publish-package
          client-payload: '{"tag": "next"}'
